insert into categorias (id, categoria, descripcion) values (1, 'Jewelery', 'Television Services');
insert into categorias (id, categoria, descripcion) values (2, 'Music', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (3, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (4, 'Computers', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (5, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (6, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (7, 'Shoes', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (8, 'Home', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (9, 'Baby', 'Electronic Components');
insert into categorias (id, categoria, descripcion) values (10, 'Garden', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (11, 'Home', 'Coal Mining');
insert into categorias (id, categoria, descripcion) values (12, 'Games', 'Farming/Seeds/Milling');
insert into categorias (id, categoria, descripcion) values (13, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (14, 'Music', 'Air Freight/Delivery Services');
insert into categorias (id, categoria, descripcion) values (15, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (16, 'Computers', 'Food Distributors');
insert into categorias (id, categoria, descripcion) values (17, 'Electronics', 'Apparel');
insert into categorias (id, categoria, descripcion) values (18, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (19, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (20, 'Health', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (21, 'Jewelery', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (22, 'Toys', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (23, 'Grocery', 'Military/Government/Technical');
insert into categorias (id, categoria, descripcion) values (24, 'Music', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (25, 'Kids', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (26, 'Games', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (27, 'Grocery', 'Water Supply');
insert into categorias (id, categoria, descripcion) values (28, 'Movies', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (29, 'Computers', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (30, 'Clothing', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (31, 'Clothing', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (32, 'Baby', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (33, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (34, 'Electronics', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (35, 'Grocery', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (36, 'Grocery', 'Auto Parts:O.E.M.');
insert into categorias (id, categoria, descripcion) values (37, 'Garden', 'Business Services');
insert into categorias (id, categoria, descripcion) values (38, 'Industrial', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (39, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (40, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (41, 'Home', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (42, 'Jewelery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (43, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (44, 'Garden', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (45, 'Baby', 'Recreational Products/Toys');
insert into categorias (id, categoria, descripcion) values (46, 'Computers', 'Advertising');
insert into categorias (id, categoria, descripcion) values (47, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (48, 'Games', 'Recreational Products/Toys');
insert into categorias (id, categoria, descripcion) values (49, 'Clothing', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (50, 'Outdoors', 'Other Consumer Services');
insert into categorias (id, categoria, descripcion) values (51, 'Electronics', 'Coal Mining');
insert into categorias (id, categoria, descripcion) values (52, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (53, 'Baby', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (54, 'Health', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (55, 'Industrial', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (56, 'Sports', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (57, 'Baby', 'Specialty Chemicals');
insert into categorias (id, categoria, descripcion) values (58, 'Music', 'Computer Manufacturing');
insert into categorias (id, categoria, descripcion) values (59, 'Tools', 'Engineering & Construction');
insert into categorias (id, categoria, descripcion) values (60, 'Home', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (61, 'Home', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (62, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (63, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (64, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (65, 'Jewelery', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (66, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (67, 'Jewelery', 'Other Specialty Stores');
insert into categorias (id, categoria, descripcion) values (68, 'Clothing', 'Television Services');
insert into categorias (id, categoria, descripcion) values (69, 'Sports', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (70, 'Movies', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (71, 'Kids', 'Package Goods/Cosmetics');
insert into categorias (id, categoria, descripcion) values (72, 'Sports', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (73, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (74, 'Beauty', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (75, 'Sports', 'Fluid Controls');
insert into categorias (id, categoria, descripcion) values (76, 'Automotive', 'Professional Services');
insert into categorias (id, categoria, descripcion) values (77, 'Tools', 'Other Specialty Stores');
insert into categorias (id, categoria, descripcion) values (78, 'Health', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (79, 'Outdoors', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (80, 'Jewelery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (81, 'Toys', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (82, 'Industrial', 'Other Specialty Stores');
insert into categorias (id, categoria, descripcion) values (83, 'Outdoors', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (84, 'Beauty', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (85, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (86, 'Computers', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (87, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (88, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (89, 'Kids', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (90, 'Baby', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (91, 'Grocery', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (92, 'Grocery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (93, 'Grocery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (94, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (95, 'Grocery', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (96, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (97, 'Industrial', 'Water Supply');
insert into categorias (id, categoria, descripcion) values (98, 'Games', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (99, 'Kids', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (100, 'Automotive', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (101, 'Automotive', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (102, 'Baby', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (103, 'Games', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (104, 'Music', 'Business Services');
insert into categorias (id, categoria, descripcion) values (105, 'Toys', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (106, 'Electronics', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (107, 'Industrial', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (108, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (109, 'Toys', 'Commercial Banks');
insert into categorias (id, categoria, descripcion) values (110, 'Tools', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (111, 'Clothing', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (112, 'Kids', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (113, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (114, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (115, 'Shoes', 'Plastic Products');
insert into categorias (id, categoria, descripcion) values (116, 'Shoes', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (117, 'Automotive', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (118, 'Jewelery', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (119, 'Music', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (120, 'Industrial', 'Multi-Sector Companies');
insert into categorias (id, categoria, descripcion) values (121, 'Garden', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (122, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (123, 'Games', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (124, 'Music', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (125, 'Industrial', 'Oilfield Services/Equipment');
insert into categorias (id, categoria, descripcion) values (126, 'Clothing', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (127, 'Books', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (128, 'Shoes', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (129, 'Health', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (130, 'Baby', 'Movies/Entertainment');
insert into categorias (id, categoria, descripcion) values (131, 'Health', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (132, 'Clothing', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (133, 'Industrial', 'Hotels/Resorts');
insert into categorias (id, categoria, descripcion) values (134, 'Health', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (135, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (136, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (137, 'Outdoors', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (138, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (139, 'Automotive', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (140, 'Movies', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (141, 'Kids', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (142, 'Toys', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (143, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (144, 'Movies', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (145, 'Books', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (146, 'Computers', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (147, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (148, 'Home', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (149, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (150, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (151, 'Sports', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (152, 'Jewelery', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (153, 'Movies', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (154, 'Garden', 'Rental/Leasing Companies');
insert into categorias (id, categoria, descripcion) values (155, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (156, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (157, 'Grocery', 'Advertising');
insert into categorias (id, categoria, descripcion) values (158, 'Sports', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (159, 'Sports', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (160, 'Electronics', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (161, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (162, 'Movies', 'n/a');
insert into categorias (id, categoria, descripcion) values (163, 'Clothing', 'Railroads');
insert into categorias (id, categoria, descripcion) values (164, 'Shoes', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (165, 'Games', 'Package Goods/Cosmetics');
insert into categorias (id, categoria, descripcion) values (166, 'Kids', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (167, 'Tools', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (168, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (169, 'Kids', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (170, 'Outdoors', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (171, 'Garden', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (172, 'Industrial', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (173, 'Toys', 'Oilfield Services/Equipment');
insert into categorias (id, categoria, descripcion) values (174, 'Home', 'Business Services');
insert into categorias (id, categoria, descripcion) values (175, 'Clothing', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (176, 'Sports', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (177, 'Beauty', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (178, 'Games', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (179, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (180, 'Garden', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (181, 'Baby', 'Newspapers/Magazines');
insert into categorias (id, categoria, descripcion) values (182, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (183, 'Computers', 'Other Consumer Services');
insert into categorias (id, categoria, descripcion) values (184, 'Baby', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (185, 'Games', 'Business Services');
insert into categorias (id, categoria, descripcion) values (186, 'Books', 'Building Products');
insert into categorias (id, categoria, descripcion) values (187, 'Electronics', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (188, 'Clothing', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (189, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (190, 'Automotive', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (191, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (192, 'Beauty', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (193, 'Jewelery', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (194, 'Jewelery', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (195, 'Sports', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (196, 'Automotive', 'Clothing/Shoe/Accessory Stores');
insert into categorias (id, categoria, descripcion) values (197, 'Movies', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (198, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (199, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (200, 'Toys', 'Precision Instruments');
insert into categorias (id, categoria, descripcion) values (201, 'Games', 'Business Services');
insert into categorias (id, categoria, descripcion) values (202, 'Home', 'Business Services');
insert into categorias (id, categoria, descripcion) values (203, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (204, 'Garden', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (205, 'Industrial', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (206, 'Clothing', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (207, 'Music', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (208, 'Automotive', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (209, 'Jewelery', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (210, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (211, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (212, 'Health', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (213, 'Music', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (214, 'Clothing', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (215, 'Jewelery', 'Computer peripheral equipment');
insert into categorias (id, categoria, descripcion) values (216, 'Computers', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (217, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (218, 'Jewelery', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (219, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (220, 'Grocery', 'Business Services');
insert into categorias (id, categoria, descripcion) values (221, 'Jewelery', 'Multi-Sector Companies');
insert into categorias (id, categoria, descripcion) values (222, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (223, 'Jewelery', 'Medical/Nursing Services');
insert into categorias (id, categoria, descripcion) values (224, 'Baby', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (225, 'Toys', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (226, 'Music', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (227, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (228, 'Movies', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (229, 'Garden', 'Clothing/Shoe/Accessory Stores');
insert into categorias (id, categoria, descripcion) values (230, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (231, 'Games', 'Diversified Commercial Services');
insert into categorias (id, categoria, descripcion) values (232, 'Books', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (233, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (234, 'Beauty', 'Business Services');
insert into categorias (id, categoria, descripcion) values (235, 'Computers', 'Medical/Nursing Services');
insert into categorias (id, categoria, descripcion) values (236, 'Home', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (237, 'Computers', 'Biotechnology: Laboratory Analytical Instruments');
insert into categorias (id, categoria, descripcion) values (238, 'Kids', 'Railroads');
insert into categorias (id, categoria, descripcion) values (239, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (240, 'Clothing', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (241, 'Garden', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (242, 'Grocery', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (243, 'Games', 'Business Services');
insert into categorias (id, categoria, descripcion) values (244, 'Clothing', 'Military/Government/Technical');
insert into categorias (id, categoria, descripcion) values (245, 'Books', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (246, 'Tools', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (247, 'Tools', 'Power Generation');
insert into categorias (id, categoria, descripcion) values (248, 'Outdoors', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (249, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (250, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (251, 'Electronics', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (252, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (253, 'Kids', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (254, 'Movies', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus');
insert into categorias (id, categoria, descripcion) values (255, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (256, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (257, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (258, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (259, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (260, 'Shoes', 'Business Services');
insert into categorias (id, categoria, descripcion) values (261, 'Toys', 'Accident &Health Insurance');
insert into categorias (id, categoria, descripcion) values (262, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (263, 'Baby', 'Business Services');
insert into categorias (id, categoria, descripcion) values (264, 'Automotive', 'Business Services');
insert into categorias (id, categoria, descripcion) values (265, 'Movies', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (266, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (267, 'Books', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (268, 'Shoes', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (269, 'Books', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (270, 'Music', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (271, 'Industrial', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (272, 'Jewelery', 'Advertising');
insert into categorias (id, categoria, descripcion) values (273, 'Health', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (274, 'Kids', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (275, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (276, 'Beauty', 'Other Consumer Services');
insert into categorias (id, categoria, descripcion) values (277, 'Garden', 'Computer Communications Equipment');
insert into categorias (id, categoria, descripcion) values (278, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (279, 'Computers', 'Apparel');
insert into categorias (id, categoria, descripcion) values (280, 'Toys', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (281, 'Clothing', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (282, 'Electronics', 'Transportation Services');
insert into categorias (id, categoria, descripcion) values (283, 'Home', 'Professional Services');
insert into categorias (id, categoria, descripcion) values (284, 'Kids', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (285, 'Sports', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (286, 'Grocery', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (287, 'Toys', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (288, 'Beauty', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (289, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (290, 'Beauty', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (291, 'Industrial', 'Business Services');
insert into categorias (id, categoria, descripcion) values (292, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (293, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (294, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (295, 'Beauty', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (296, 'Beauty', 'Diversified Commercial Services');
insert into categorias (id, categoria, descripcion) values (297, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (298, 'Computers', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (299, 'Tools', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (300, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (301, 'Grocery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (302, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (303, 'Electronics', 'Auto Manufacturing');
insert into categorias (id, categoria, descripcion) values (304, 'Games', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (305, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (306, 'Toys', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (307, 'Movies', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (308, 'Industrial', 'Auto Manufacturing');
insert into categorias (id, categoria, descripcion) values (309, 'Music', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (310, 'Electronics', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (311, 'Music', 'Advertising');
insert into categorias (id, categoria, descripcion) values (312, 'Jewelery', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (313, 'Tools', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (314, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (315, 'Computers', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (316, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (317, 'Toys', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (318, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (319, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (320, 'Beauty', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (321, 'Shoes', 'Specialty Chemicals');
insert into categorias (id, categoria, descripcion) values (322, 'Books', 'Business Services');
insert into categorias (id, categoria, descripcion) values (323, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (324, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (325, 'Jewelery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (326, 'Beauty', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (327, 'Sports', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (328, 'Jewelery', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (329, 'Music', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (330, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (331, 'Games', 'Railroads');
insert into categorias (id, categoria, descripcion) values (332, 'Sports', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (333, 'Electronics', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (334, 'Garden', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (335, 'Books', 'Trucking Freight/Courier Services');
insert into categorias (id, categoria, descripcion) values (336, 'Health', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (337, 'Computers', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (338, 'Sports', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (339, 'Automotive', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (340, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (341, 'Computers', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (342, 'Music', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (343, 'Grocery', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (344, 'Outdoors', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (345, 'Toys', 'Advertising');
insert into categorias (id, categoria, descripcion) values (346, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (347, 'Sports', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (348, 'Books', 'n/a');
insert into categorias (id, categoria, descripcion) values (349, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (350, 'Garden', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (351, 'Grocery', 'Computer Communications Equipment');
insert into categorias (id, categoria, descripcion) values (352, 'Music', 'n/a');
insert into categorias (id, categoria, descripcion) values (353, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (354, 'Jewelery', 'Auto Manufacturing');
insert into categorias (id, categoria, descripcion) values (355, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (356, 'Toys', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (357, 'Music', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (358, 'Garden', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (359, 'Grocery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (360, 'Music', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (361, 'Industrial', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (362, 'Shoes', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (363, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (364, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (365, 'Beauty', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (366, 'Industrial', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (367, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (368, 'Home', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (369, 'Games', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (370, 'Sports', 'Computer Communications Equipment');
insert into categorias (id, categoria, descripcion) values (371, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (372, 'Toys', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (373, 'Outdoors', 'Services-Misc. Amusement & Recreation');
insert into categorias (id, categoria, descripcion) values (374, 'Health', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (375, 'Kids', 'Business Services');
insert into categorias (id, categoria, descripcion) values (376, 'Books', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (377, 'Toys', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (378, 'Books', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (379, 'Music', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (380, 'Music', 'Consumer Electronics/Appliances');
insert into categorias (id, categoria, descripcion) values (381, 'Electronics', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (382, 'Shoes', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (383, 'Beauty', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (384, 'Garden', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (385, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (386, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (387, 'Industrial', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (388, 'Electronics', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (389, 'Grocery', 'Farming/Seeds/Milling');
insert into categorias (id, categoria, descripcion) values (390, 'Movies', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (391, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (392, 'Automotive', 'Professional Services');
insert into categorias (id, categoria, descripcion) values (393, 'Outdoors', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (394, 'Games', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (395, 'Games', 'Forest Products');
insert into categorias (id, categoria, descripcion) values (396, 'Home', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (397, 'Garden', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (398, 'Jewelery', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (399, 'Industrial', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (400, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (401, 'Music', 'Television Services');
insert into categorias (id, categoria, descripcion) values (402, 'Kids', 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)');
insert into categorias (id, categoria, descripcion) values (403, 'Shoes', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (404, 'Outdoors', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (405, 'Sports', 'Pollution Control Equipment');
insert into categorias (id, categoria, descripcion) values (406, 'Baby', 'Integrated oil Companies');
insert into categorias (id, categoria, descripcion) values (407, 'Garden', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (408, 'Baby', 'Department/Specialty Retail Stores');
insert into categorias (id, categoria, descripcion) values (409, 'Baby', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (410, 'Music', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (411, 'Clothing', 'Package Goods/Cosmetics');
insert into categorias (id, categoria, descripcion) values (412, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (413, 'Outdoors', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (414, 'Beauty', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (415, 'Sports', 'Apparel');
insert into categorias (id, categoria, descripcion) values (416, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (417, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (418, 'Beauty', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (419, 'Toys', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (420, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (421, 'Garden', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (422, 'Computers', 'Oil/Gas Transmission');
insert into categorias (id, categoria, descripcion) values (423, 'Games', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (424, 'Music', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (425, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (426, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (427, 'Grocery', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (428, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (429, 'Tools', 'Building Products');
insert into categorias (id, categoria, descripcion) values (430, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (431, 'Tools', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (432, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (433, 'Kids', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (434, 'Automotive', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (435, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (436, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (437, 'Music', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (438, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (439, 'Music', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (440, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (441, 'Beauty', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (442, 'Music', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (443, 'Industrial', 'Food Chains');
insert into categorias (id, categoria, descripcion) values (444, 'Computers', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (445, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (446, 'Sports', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (447, 'Books', 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)');
insert into categorias (id, categoria, descripcion) values (448, 'Books', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (449, 'Home', 'Other Specialty Stores');
insert into categorias (id, categoria, descripcion) values (450, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (451, 'Automotive', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (452, 'Home', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (453, 'Computers', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (454, 'Garden', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (455, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (456, 'Beauty', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (457, 'Grocery', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (458, 'Toys', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (459, 'Garden', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (460, 'Beauty', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (461, 'Tools', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (462, 'Tools', 'Clothing/Shoe/Accessory Stores');
insert into categorias (id, categoria, descripcion) values (463, 'Toys', 'Advertising');
insert into categorias (id, categoria, descripcion) values (464, 'Games', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (465, 'Computers', 'Publishing');
insert into categorias (id, categoria, descripcion) values (466, 'Movies', 'Commercial Banks');
insert into categorias (id, categoria, descripcion) values (467, 'Jewelery', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (468, 'Health', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (469, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (470, 'Computers', 'Biotechnology: Commercial Physical & Biological Resarch');
insert into categorias (id, categoria, descripcion) values (471, 'Toys', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (472, 'Toys', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (473, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (474, 'Baby', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (475, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (476, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (477, 'Music', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (478, 'Sports', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (479, 'Games', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (480, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (481, 'Beauty', 'Business Services');
insert into categorias (id, categoria, descripcion) values (482, 'Beauty', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (483, 'Health', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (484, 'Computers', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (485, 'Automotive', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (486, 'Toys', 'Television Services');
insert into categorias (id, categoria, descripcion) values (487, 'Music', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (488, 'Toys', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (489, 'Games', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (490, 'Sports', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (491, 'Books', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (492, 'Tools', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (493, 'Clothing', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (494, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (495, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (496, 'Baby', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (497, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (498, 'Home', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (499, 'Computers', 'Computer Manufacturing');
insert into categorias (id, categoria, descripcion) values (500, 'Baby', 'Agricultural Chemicals');
insert into categorias (id, categoria, descripcion) values (501, 'Clothing', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (502, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (503, 'Health', 'Agricultural Chemicals');
insert into categorias (id, categoria, descripcion) values (504, 'Home', 'Environmental Services');
insert into categorias (id, categoria, descripcion) values (505, 'Beauty', 'Military/Government/Technical');
insert into categorias (id, categoria, descripcion) values (506, 'Computers', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (507, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (508, 'Tools', 'Precision Instruments');
insert into categorias (id, categoria, descripcion) values (509, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (510, 'Computers', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (511, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (512, 'Jewelery', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (513, 'Outdoors', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (514, 'Clothing', 'Office Equipment/Supplies/Services');
insert into categorias (id, categoria, descripcion) values (515, 'Outdoors', 'Business Services');
insert into categorias (id, categoria, descripcion) values (516, 'Music', 'Trucking Freight/Courier Services');
insert into categorias (id, categoria, descripcion) values (517, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (518, 'Health', 'Beverages (Production/Distribution)');
insert into categorias (id, categoria, descripcion) values (519, 'Games', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (520, 'Tools', 'Electronic Components');
insert into categorias (id, categoria, descripcion) values (521, 'Movies', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (522, 'Toys', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (523, 'Books', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (524, 'Grocery', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (525, 'Baby', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (526, 'Toys', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (527, 'Home', 'Business Services');
insert into categorias (id, categoria, descripcion) values (528, 'Automotive', 'Diversified Commercial Services');
insert into categorias (id, categoria, descripcion) values (529, 'Tools', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (530, 'Computers', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (531, 'Outdoors', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (532, 'Grocery', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (533, 'Outdoors', 'Commercial Banks');
insert into categorias (id, categoria, descripcion) values (534, 'Baby', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (535, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (536, 'Automotive', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (537, 'Shoes', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (538, 'Toys', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (539, 'Grocery', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (540, 'Books', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (541, 'Tools', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (542, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (543, 'Computers', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (544, 'Clothing', 'Miscellaneous manufacturing industries');
insert into categorias (id, categoria, descripcion) values (545, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (546, 'Garden', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (547, 'Games', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (548, 'Clothing', 'Oilfield Services/Equipment');
insert into categorias (id, categoria, descripcion) values (549, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (550, 'Industrial', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (551, 'Movies', 'Electronic Components');
insert into categorias (id, categoria, descripcion) values (552, 'Outdoors', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (553, 'Health', 'Specialty Chemicals');
insert into categorias (id, categoria, descripcion) values (554, 'Shoes', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (555, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (556, 'Outdoors', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (557, 'Music', 'Business Services');
insert into categorias (id, categoria, descripcion) values (558, 'Music', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (559, 'Grocery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (560, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (561, 'Health', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (562, 'Movies', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (563, 'Tools', 'Retail: Computer Software & Peripheral Equipment');
insert into categorias (id, categoria, descripcion) values (564, 'Shoes', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (565, 'Shoes', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (566, 'Electronics', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (567, 'Outdoors', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (568, 'Automotive', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (569, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (570, 'Music', 'Radio And Television Broadcasting And Communications Equipment');
insert into categorias (id, categoria, descripcion) values (571, 'Grocery', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (572, 'Home', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (573, 'Beauty', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (574, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (575, 'Beauty', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (576, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (577, 'Garden', 'Agricultural Chemicals');
insert into categorias (id, categoria, descripcion) values (578, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (579, 'Garden', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (580, 'Tools', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (581, 'Beauty', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (582, 'Home', 'Other Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (583, 'Garden', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (584, 'Outdoors', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (585, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (586, 'Beauty', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (587, 'Electronics', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (588, 'Baby', 'Beverages (Production/Distribution)');
insert into categorias (id, categoria, descripcion) values (589, 'Beauty', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (590, 'Clothing', 'Major Chemicals');
insert into categorias (id, categoria, descripcion) values (591, 'Home', 'Television Services');
insert into categorias (id, categoria, descripcion) values (592, 'Electronics', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (593, 'Shoes', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (594, 'Grocery', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (595, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (596, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (597, 'Industrial', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (598, 'Beauty', 'Hotels/Resorts');
insert into categorias (id, categoria, descripcion) values (599, 'Health', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (600, 'Books', 'n/a');
insert into categorias (id, categoria, descripcion) values (601, 'Beauty', 'Transportation Services');
insert into categorias (id, categoria, descripcion) values (602, 'Outdoors', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (603, 'Computers', 'Building Materials');
insert into categorias (id, categoria, descripcion) values (604, 'Books', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (605, 'Jewelery', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (606, 'Beauty', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (607, 'Industrial', 'RETAIL: Building Materials');
insert into categorias (id, categoria, descripcion) values (608, 'Movies', 'Plastic Products');
insert into categorias (id, categoria, descripcion) values (609, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (610, 'Home', 'RETAIL: Building Materials');
insert into categorias (id, categoria, descripcion) values (611, 'Games', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (612, 'Clothing', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (613, 'Baby', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (614, 'Health', 'Consumer Electronics/Appliances');
insert into categorias (id, categoria, descripcion) values (615, 'Tools', 'Medical Specialities');
insert into categorias (id, categoria, descripcion) values (616, 'Music', 'Construction/Ag Equipment/Trucks');
insert into categorias (id, categoria, descripcion) values (617, 'Beauty', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (618, 'Movies', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (619, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (620, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (621, 'Electronics', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (622, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (623, 'Music', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (624, 'Toys', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (625, 'Outdoors', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (626, 'Home', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (627, 'Beauty', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (628, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (629, 'Automotive', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (630, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (631, 'Outdoors', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (632, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (633, 'Books', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (634, 'Jewelery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (635, 'Baby', 'Diversified Commercial Services');
insert into categorias (id, categoria, descripcion) values (636, 'Baby', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (637, 'Baby', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (638, 'Home', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (639, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (640, 'Books', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (641, 'Electronics', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (642, 'Clothing', 'Commercial Banks');
insert into categorias (id, categoria, descripcion) values (643, 'Electronics', 'Specialty Chemicals');
insert into categorias (id, categoria, descripcion) values (644, 'Beauty', 'Auto Parts:O.E.M.');
insert into categorias (id, categoria, descripcion) values (645, 'Kids', 'Business Services');
insert into categorias (id, categoria, descripcion) values (646, 'Home', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (647, 'Grocery', 'Power Generation');
insert into categorias (id, categoria, descripcion) values (648, 'Games', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (649, 'Garden', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (650, 'Grocery', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (651, 'Automotive', 'Banks');
insert into categorias (id, categoria, descripcion) values (652, 'Books', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (653, 'Industrial', 'Business Services');
insert into categorias (id, categoria, descripcion) values (654, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (655, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (656, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (657, 'Music', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (658, 'Books', 'Paper');
insert into categorias (id, categoria, descripcion) values (659, 'Home', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (660, 'Industrial', 'Aerospace');
insert into categorias (id, categoria, descripcion) values (661, 'Home', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (662, 'Home', 'Air Freight/Delivery Services');
insert into categorias (id, categoria, descripcion) values (663, 'Industrial', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (664, 'Industrial', 'Beverages (Production/Distribution)');
insert into categorias (id, categoria, descripcion) values (665, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (666, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (667, 'Outdoors', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (668, 'Garden', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (669, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (670, 'Industrial', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (671, 'Movies', 'Building Products');
insert into categorias (id, categoria, descripcion) values (672, 'Jewelery', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (673, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (674, 'Home', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (675, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (676, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (677, 'Home', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (678, 'Movies', 'n/a');
insert into categorias (id, categoria, descripcion) values (679, 'Baby', 'Medical/Nursing Services');
insert into categorias (id, categoria, descripcion) values (680, 'Sports', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (681, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (682, 'Electronics', 'n/a');
insert into categorias (id, categoria, descripcion) values (683, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (684, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (685, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (686, 'Industrial', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (687, 'Outdoors', 'n/a');
insert into categorias (id, categoria, descripcion) values (688, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (689, 'Clothing', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (690, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (691, 'Toys', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (692, 'Baby', 'Transportation Services');
insert into categorias (id, categoria, descripcion) values (693, 'Tools', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (694, 'Automotive', 'Metal Fabrications');
insert into categorias (id, categoria, descripcion) values (695, 'Toys', 'Business Services');
insert into categorias (id, categoria, descripcion) values (696, 'Beauty', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (697, 'Beauty', 'Diversified Commercial Services');
insert into categorias (id, categoria, descripcion) values (698, 'Movies', 'Clothing/Shoe/Accessory Stores');
insert into categorias (id, categoria, descripcion) values (699, 'Health', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (700, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (701, 'Health', 'Radio And Television Broadcasting And Communications Equipment');
insert into categorias (id, categoria, descripcion) values (702, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (703, 'Music', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (704, 'Outdoors', 'Pollution Control Equipment');
insert into categorias (id, categoria, descripcion) values (705, 'Industrial', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (706, 'Clothing', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (707, 'Home', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (708, 'Baby', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (709, 'Music', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (710, 'Shoes', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (711, 'Clothing', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (712, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (713, 'Home', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (714, 'Electronics', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (715, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (716, 'Music', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (717, 'Clothing', 'Recreational Products/Toys');
insert into categorias (id, categoria, descripcion) values (718, 'Clothing', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (719, 'Automotive', 'Business Services');
insert into categorias (id, categoria, descripcion) values (720, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (721, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (722, 'Movies', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (723, 'Beauty', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (724, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (725, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (726, 'Sports', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (727, 'Games', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (728, 'Music', 'Agricultural Chemicals');
insert into categorias (id, categoria, descripcion) values (729, 'Movies', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (730, 'Toys', 'Hotels/Resorts');
insert into categorias (id, categoria, descripcion) values (731, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (732, 'Garden', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (733, 'Jewelery', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (734, 'Games', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (735, 'Kids', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (736, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (737, 'Books', 'Food Chains');
insert into categorias (id, categoria, descripcion) values (738, 'Baby', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (739, 'Electronics', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (740, 'Games', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (741, 'Tools', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into categorias (id, categoria, descripcion) values (742, 'Jewelery', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (743, 'Toys', 'n/a');
insert into categorias (id, categoria, descripcion) values (744, 'Movies', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (745, 'Kids', 'Biotechnology: Commercial Physical & Biological Resarch');
insert into categorias (id, categoria, descripcion) values (746, 'Automotive', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (747, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (748, 'Kids', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (749, 'Music', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (750, 'Baby', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (751, 'Sports', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (752, 'Home', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (753, 'Baby', 'Specialty Foods');
insert into categorias (id, categoria, descripcion) values (754, 'Toys', 'Diversified Financial Services');
insert into categorias (id, categoria, descripcion) values (755, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (756, 'Tools', 'Farming/Seeds/Milling');
insert into categorias (id, categoria, descripcion) values (757, 'Movies', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (758, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (759, 'Grocery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (760, 'Electronics', 'Construction/Ag Equipment/Trucks');
insert into categorias (id, categoria, descripcion) values (761, 'Tools', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (762, 'Baby', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (763, 'Books', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (764, 'Games', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (765, 'Computers', 'Advertising');
insert into categorias (id, categoria, descripcion) values (766, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (767, 'Grocery', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (768, 'Clothing', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (769, 'Industrial', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (770, 'Baby', 'Other Consumer Services');
insert into categorias (id, categoria, descripcion) values (771, 'Music', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (772, 'Health', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (773, 'Beauty', 'Office Equipment/Supplies/Services');
insert into categorias (id, categoria, descripcion) values (774, 'Jewelery', 'Beverages (Production/Distribution)');
insert into categorias (id, categoria, descripcion) values (775, 'Toys', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (776, 'Outdoors', 'Business Services');
insert into categorias (id, categoria, descripcion) values (777, 'Automotive', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (778, 'Toys', 'Accident &Health Insurance');
insert into categorias (id, categoria, descripcion) values (779, 'Automotive', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (780, 'Health', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (781, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (782, 'Health', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (783, 'Industrial', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (784, 'Books', 'Business Services');
insert into categorias (id, categoria, descripcion) values (785, 'Outdoors', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (786, 'Toys', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (787, 'Home', 'Commercial Banks');
insert into categorias (id, categoria, descripcion) values (788, 'Industrial', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (789, 'Beauty', 'Multi-Sector Companies');
insert into categorias (id, categoria, descripcion) values (790, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (791, 'Home', 'n/a');
insert into categorias (id, categoria, descripcion) values (792, 'Grocery', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (793, 'Health', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (794, 'Toys', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (795, 'Industrial', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (796, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (797, 'Tools', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (798, 'Electronics', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (799, 'Baby', 'Agricultural Chemicals');
insert into categorias (id, categoria, descripcion) values (800, 'Electronics', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (801, 'Beauty', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (802, 'Outdoors', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (803, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (804, 'Automotive', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (805, 'Toys', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (806, 'Electronics', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (807, 'Grocery', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (808, 'Baby', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (809, 'Baby', 'Marine Transportation');
insert into categorias (id, categoria, descripcion) values (810, 'Beauty', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (811, 'Toys', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (812, 'Health', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (813, 'Industrial', 'Forest Products');
insert into categorias (id, categoria, descripcion) values (814, 'Garden', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (815, 'Computers', 'Auto Manufacturing');
insert into categorias (id, categoria, descripcion) values (816, 'Movies', 'n/a');
insert into categorias (id, categoria, descripcion) values (817, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (818, 'Books', 'Paper');
insert into categorias (id, categoria, descripcion) values (819, 'Books', 'Consumer Specialties');
insert into categorias (id, categoria, descripcion) values (820, 'Electronics', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (821, 'Movies', 'Business Services');
insert into categorias (id, categoria, descripcion) values (822, 'Automotive', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (823, 'Shoes', 'n/a');
insert into categorias (id, categoria, descripcion) values (824, 'Sports', 'Business Services');
insert into categorias (id, categoria, descripcion) values (825, 'Books', 'Investment Managers');
insert into categorias (id, categoria, descripcion) values (826, 'Shoes', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (827, 'Books', 'Military/Government/Technical');
insert into categorias (id, categoria, descripcion) values (828, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (829, 'Health', 'Professional Services');
insert into categorias (id, categoria, descripcion) values (830, 'Books', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (831, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (832, 'Garden', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (833, 'Sports', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (834, 'Books', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (835, 'Electronics', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (836, 'Health', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (837, 'Music', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (838, 'Sports', 'Finance: Consumer Services');
insert into categorias (id, categoria, descripcion) values (839, 'Industrial', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (840, 'Automotive', 'Miscellaneous manufacturing industries');
insert into categorias (id, categoria, descripcion) values (841, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (842, 'Health', 'Newspapers/Magazines');
insert into categorias (id, categoria, descripcion) values (843, 'Outdoors', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (844, 'Industrial', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (845, 'Health', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (846, 'Clothing', 'Specialty Chemicals');
insert into categorias (id, categoria, descripcion) values (847, 'Movies', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (848, 'Baby', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (849, 'Computers', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (850, 'Clothing', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (851, 'Jewelery', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (852, 'Outdoors', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (853, 'Toys', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (854, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (855, 'Garden', 'Industrial Specialties');
insert into categorias (id, categoria, descripcion) values (856, 'Shoes', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (857, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (858, 'Computers', 'Food Chains');
insert into categorias (id, categoria, descripcion) values (859, 'Sports', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (860, 'Computers', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (861, 'Sports', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (862, 'Home', 'Consumer Electronics/Appliances');
insert into categorias (id, categoria, descripcion) values (863, 'Industrial', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (864, 'Sports', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (865, 'Industrial', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (866, 'Health', 'n/a');
insert into categorias (id, categoria, descripcion) values (867, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (868, 'Books', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (869, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (870, 'Garden', 'Natural Gas Distribution');
insert into categorias (id, categoria, descripcion) values (871, 'Jewelery', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (872, 'Garden', 'Packaged Foods');
insert into categorias (id, categoria, descripcion) values (873, 'Books', 'Automotive Aftermarket');
insert into categorias (id, categoria, descripcion) values (874, 'Music', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (875, 'Beauty', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (876, 'Baby', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (877, 'Automotive', 'Retail: Computer Software & Peripheral Equipment');
insert into categorias (id, categoria, descripcion) values (878, 'Tools', 'Specialty Foods');
insert into categorias (id, categoria, descripcion) values (879, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (880, 'Tools', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (881, 'Grocery', 'Auto Manufacturing');
insert into categorias (id, categoria, descripcion) values (882, 'Toys', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (883, 'Health', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (884, 'Health', 'Recreational Products/Toys');
insert into categorias (id, categoria, descripcion) values (885, 'Computers', 'Environmental Services');
insert into categorias (id, categoria, descripcion) values (886, 'Tools', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (887, 'Beauty', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (888, 'Books', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (889, 'Industrial', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (890, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (891, 'Beauty', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (892, 'Home', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (893, 'Computers', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (894, 'Health', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (895, 'Beauty', 'Multi-Sector Companies');
insert into categorias (id, categoria, descripcion) values (896, 'Sports', 'n/a');
insert into categorias (id, categoria, descripcion) values (897, 'Health', 'Miscellaneous');
insert into categorias (id, categoria, descripcion) values (898, 'Outdoors', 'Advertising');
insert into categorias (id, categoria, descripcion) values (899, 'Movies', 'n/a');
insert into categorias (id, categoria, descripcion) values (900, 'Clothing', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (901, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (902, 'Electronics', 'Auto Parts:O.E.M.');
insert into categorias (id, categoria, descripcion) values (903, 'Jewelery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (904, 'Outdoors', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (905, 'Health', 'Business Services');
insert into categorias (id, categoria, descripcion) values (906, 'Jewelery', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (907, 'Grocery', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (908, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (909, 'Jewelery', 'n/a');
insert into categorias (id, categoria, descripcion) values (910, 'Tools', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (911, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (912, 'Electronics', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (913, 'Games', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (914, 'Grocery', 'Savings Institutions');
insert into categorias (id, categoria, descripcion) values (915, 'Books', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (916, 'Industrial', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (917, 'Shoes', 'Television Services');
insert into categorias (id, categoria, descripcion) values (918, 'Books', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (919, 'Toys', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (920, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (921, 'Sports', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (922, 'Home', 'Precious Metals');
insert into categorias (id, categoria, descripcion) values (923, 'Grocery', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (924, 'Home', 'Retail: Computer Software & Peripheral Equipment');
insert into categorias (id, categoria, descripcion) values (925, 'Sports', 'Restaurants');
insert into categorias (id, categoria, descripcion) values (926, 'Health', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (927, 'Music', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (928, 'Electronics', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (929, 'Baby', 'Power Generation');
insert into categorias (id, categoria, descripcion) values (930, 'Automotive', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (931, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (932, 'Jewelery', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (933, 'Clothing', 'n/a');
insert into categorias (id, categoria, descripcion) values (934, 'Clothing', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (935, 'Kids', 'Auto Parts:O.E.M.');
insert into categorias (id, categoria, descripcion) values (936, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (937, 'Beauty', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (938, 'Garden', 'Business Services');
insert into categorias (id, categoria, descripcion) values (939, 'Clothing', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (940, 'Outdoors', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (941, 'Toys', 'Aerospace');
insert into categorias (id, categoria, descripcion) values (942, 'Electronics', 'Major Banks');
insert into categorias (id, categoria, descripcion) values (943, 'Home', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into categorias (id, categoria, descripcion) values (944, 'Games', 'Broadcasting');
insert into categorias (id, categoria, descripcion) values (945, 'Computers', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (946, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (947, 'Industrial', 'Medical/Dental Instruments');
insert into categorias (id, categoria, descripcion) values (948, 'Automotive', 'Business Services');
insert into categorias (id, categoria, descripcion) values (949, 'Jewelery', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (950, 'Automotive', 'Water Supply');
insert into categorias (id, categoria, descripcion) values (951, 'Electronics', 'Real Estate');
insert into categorias (id, categoria, descripcion) values (952, 'Garden', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (953, 'Sports', 'Office Equipment/Supplies/Services');
insert into categorias (id, categoria, descripcion) values (954, 'Outdoors', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (955, 'Toys', 'Business Services');
insert into categorias (id, categoria, descripcion) values (956, 'Garden', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (957, 'Kids', 'n/a');
insert into categorias (id, categoria, descripcion) values (958, 'Beauty', 'Farming/Seeds/Milling');
insert into categorias (id, categoria, descripcion) values (959, 'Books', 'Computer Software: Prepackaged Software');
insert into categorias (id, categoria, descripcion) values (960, 'Automotive', 'Home Furnishings');
insert into categorias (id, categoria, descripcion) values (961, 'Beauty', 'RETAIL: Building Materials');
insert into categorias (id, categoria, descripcion) values (962, 'Kids', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (963, 'Beauty', 'n/a');
insert into categorias (id, categoria, descripcion) values (964, 'Computers', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (965, 'Shoes', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (966, 'Shoes', 'Air Freight/Delivery Services');
insert into categorias (id, categoria, descripcion) values (967, 'Toys', 'Computer Software: Programming, Data Processing');
insert into categorias (id, categoria, descripcion) values (968, 'Industrial', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (969, 'Electronics', 'Major Pharmaceuticals');
insert into categorias (id, categoria, descripcion) values (970, 'Music', 'Life Insurance');
insert into categorias (id, categoria, descripcion) values (971, 'Books', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (972, 'Computers', 'n/a');
insert into categorias (id, categoria, descripcion) values (973, 'Games', 'Plastic Products');
insert into categorias (id, categoria, descripcion) values (974, 'Industrial', 'n/a');
insert into categorias (id, categoria, descripcion) values (975, 'Beauty', 'Aerospace');
insert into categorias (id, categoria, descripcion) values (976, 'Sports', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (977, 'Games', 'n/a');
insert into categorias (id, categoria, descripcion) values (978, 'Beauty', 'Electrical Products');
insert into categorias (id, categoria, descripcion) values (979, 'Grocery', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (980, 'Shoes', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (981, 'Jewelery', 'Property-Casualty Insurers');
insert into categorias (id, categoria, descripcion) values (982, 'Sports', 'Homebuilding');
insert into categorias (id, categoria, descripcion) values (983, 'Clothing', 'Oil & Gas Production');
insert into categorias (id, categoria, descripcion) values (984, 'Tools', 'EDP Services');
insert into categorias (id, categoria, descripcion) values (985, 'Kids', 'Real Estate Investment Trusts');
insert into categorias (id, categoria, descripcion) values (986, 'Garden', 'n/a');
insert into categorias (id, categoria, descripcion) values (987, 'Grocery', 'Package Goods/Cosmetics');
insert into categorias (id, categoria, descripcion) values (988, 'Baby', 'n/a');
insert into categorias (id, categoria, descripcion) values (989, 'Baby', 'Electric Utilities: Central');
insert into categorias (id, categoria, descripcion) values (990, 'Outdoors', 'Telecommunications Equipment');
insert into categorias (id, categoria, descripcion) values (991, 'Games', 'Hospital/Nursing Management');
insert into categorias (id, categoria, descripcion) values (992, 'Tools', 'n/a');
insert into categorias (id, categoria, descripcion) values (993, 'Beauty', 'Investment Bankers/Brokers/Service');
insert into categorias (id, categoria, descripcion) values (994, 'Health', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (995, 'Tools', 'Oil Refining/Marketing');
insert into categorias (id, categoria, descripcion) values (996, 'Movies', 'Semiconductors');
insert into categorias (id, categoria, descripcion) values (997, 'Outdoors', 'Industrial Machinery/Components');
insert into categorias (id, categoria, descripcion) values (998, 'Automotive', 'n/a');
insert into categorias (id, categoria, descripcion) values (999, 'Grocery', 'n/a');
insert into categorias (id, categoria, descripcion) values (1000, 'Tools', 'Computer Software: Prepackaged Software');
